<a href="https://colab.research.google.com/github/Saba-a11/Crypto/blob/main/Get_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install yfinance

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting yfinance
  Downloading yfinance-0.2.12-py2.py3-none-any.whl (59 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.2/59.2 KB 4.0 MB/s eta 0:00:00
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.8/dist-packages (from yfinance) (0.0.11)
Collecting html5lib>=1.1
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.2/112.2 KB 9.3 MB/s eta 0:00:00
Collecting cryptography>=3.3.2
  Downloading cryptography-39.0.1-cp36-abi3-manylinux_2_28_x86_64.whl (4.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 66.8 MB/s eta 0:00:00
Collecting beautifulsoup4>=4.11.1
  Downloading beautifulsoup4-4.11.2-py3-none-any.whl (129 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 KB 13.5 MB/s eta 0:00:00
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.3.5)
Requirement already satisfied: lxml>=4.9.1 in /usr/local/lib/python3.8/dist-packages (from yfinance) (4.9.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.22.4)
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.4.4)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.8/dist-packages (from yfinance) (2022.7.1)
Collecting frozendict>=2.3.4
  Downloading frozendict-2.3.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (111 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.2/111.2 KB 14.1 MB/s eta 0:00:00
Collecting requests>=2.26
  Downloading requests-2.28.2-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 6.4 MB/s eta 0:00:00
Collecting soupsieve>1.2
  Downloading soupsieve-2.4-py3-none-any.whl (37 kB)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.8/dist-packages (from cryptography>=3.3.2->yfinance) (1.15.1)
Requirement already satisfied: webencodings in /usr/local/lib/python3.8/dist-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.8/dist-packages (from html5lib>=1.1->yfinance) (1.15.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (3.0.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (2.10)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.12->cryptography>=3.3.2->yfinance) (2.21)
Installing collected packages: soupsieve, requests, html5lib, frozendict, cryptography, beautifulsoup4, yfinance
  Attempting uninstall: requests
    Found existing installation: requests 2.25.1
    Uninstalling requests-2.25.1:
      Successfully uninstalled requests-2.25.1
  Attempting uninstall: html5lib
    Found existing installation: html5lib 1.0.1
    Uninstalling html5lib-1.0.1:
      Successfully uninstalled html5lib-1.0.1
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3
Successfully installed beautifulsoup4-4.11.2 cryptography-39.0.1 frozendict-2.3.5 html5lib-1.1 requests-2.28.2 soupsieve-2.4 yfinance-0.2.12

In [41]:
import yfinance as yf

In [42]:
data = yf.download("AAPL", "2017-01-01", "2023-01-01")
data.head()

[*********************100%***********************]  1 of 1 completed

                 Open       High        Low      Close  Adj Close     Volume
Date
2017-01-03  28.950001  29.082500  28.690001  29.037500  27.133327  115127600
2017-01-04  28.962500  29.127501  28.937500  29.004999  27.102959   84472400
2017-01-05  28.980000  29.215000  28.952499  29.152500  27.240782   88774400
2017-01-06  29.195000  29.540001  29.117500  29.477501  27.544470  127007600
2017-01-09  29.487499  29.857500  29.485001  29.747499  27.796768  134247600

In [46]:
curl = "https://poloniex.com/public?command=returnChartData&currencyPair=BTC_XMR&start=1546300800&end=1546646400&period=14400"

In [47]:
import requests
import json
import pandas as pd

req = requests.get(curl)
data = json.loads(req.text)
df = pd.DataFrame(data)
df

,date,high,low,open,close,volume,quoteVolume,weightedAverage
0,1546300800000,0.012321,0.012105,0.012274,0.012247,938.52,11.47474,0.012226
1,1546315200000,0.012357,0.012180,0.012254,0.012230,567.59,6.965434,0.012271
2,1546329600000,0.012342,0.012173,0.012231,0.012283,578.44,7.109576,0.01229
3,1546344000000,0.012379,0.012248,0.012291,0.012291,743.25,9.145455,0.012304
4,1546358400000,0.012458,0.012251,0.012280,0.012458,1696.31,20.975011,0.012365
5,1546372800000,0.012648,0.012391,0.012429,0.012495,2322.77,29.140454,0.012545
6,1546387200000,0.012599,0.012431,0.012495,0.012479,799.56,10.031364,0.012546
7,1546401600000,0.012784,0.012479,0.012479,0.012752,1564.66,19.837234,0.012678
8,1546416000000,0.012865,0.012574,0.012752,0.012760,4744.76,60.399254,0.012729
9,1546430400000,0.013176,0.012692,0.012760,0.013000,7678.08,99.558343,0.012966
10,1546444800000,0.013920,0.012994,0.012994,0.013575,11686.69,159.009184,0.013605
11,1546459200000,0.013800,0.013161,0.013575,0.013290,4677.28,62.607226,0.013385
12,1546473600000,0.013368,0.013080,0.013290,0.013156,2309.02,30.405675,0.013168
13,1546488000000,0.013234,0.013092,0.013156,0.013154,643.58,8.467947,0.013157
14,1546502400000,0.013300,0.012918,0.013154,0.012975,3451.78,45.127696,0.013073
15,1546516800000,0.013073,0.012900,0.012975,0.013013,2729.5,35.38764,0.012964
16,1546531200000,0.013073,0.012905,0.013013,0.012945,1894.35,24.56854,0.012969
17,1546545600000,0.013045,0.012908,0.012945,0.012938,1996.31,25.849946,0.012948
18,1546560000000,0.013044,0.012917,0.012942,0.012930,1906.56,24.698995,0.012954
19,1546574400000,0.013170,0.012920,0.012930,0.013093,1307.21,17.054155,0.013046
20,1546588800000,0.013196,0.013014,0.013093,0.013102,1416.8,18.513895,0.013067
21,1546603200000,0.013304,0.012949,0.013150,0.013228,1574.23,20.630293,0.013105
22,1546617600000,0.013298,0.013109,0.013229,0.013205,1443.14,19.064247,0.01321
23,1546632000000,0.013279,0.012956,0.013190,0.013050,1899.11,24.870417,0.013095
24,1546646400000,0.013279,0.013040,0.013050,0.013190,1221.53,16.099599,0.013179

## Other Sources:


*   Quandl
*   Financial Modeling Prep
*   Cryptowizards.net

In [48]:
df.to_csv("Sample_Data.csv")